### ISSUE TITLE
asking permission access to media

### ISSUE THREAD

**Issue by heeringa0** [addpipe/simple-web-audio-recorder-demo#4]
This is a wonderful demo!

I made an R / Shiny version which is available at: https://github.com/heeringa0/simple-web-audio-recorder

I have a question about the asking for permission to get access to the user's microphone. Within one session the user needs to give permission once, i.e. only the first time when pressing 'Record´ when using Google Chrome / Chromium / Opera and when https is used. However, when using Firefox, each time you press on 'Record' you need to give permission again (even when using https).

Is there a (simple) fix that forces Firefox to behave like Google Chrome?

**Comment by octavn** [comment]
> Is there a (simple) fix that forces Firefox to behave like Google Chrome?

No. The Firefox _Allow_ permission is not persistent by default but users are given the option to make their permission persistent:

<img width="549" alt="Screenshot 2019-06-24 at 14 10 31" src="https://user-images.githubusercontent.com/6663020/60017895-27450a00-968a-11e9-8a11-33455ff26e1e.png">





**It is my opinion that Chrome should behave more like Firefox.** In Chrome, permissions are persistent by default long term so a website for which you've previously granted permission could be highjacked 6 months later and access your camera without you being prompted.

**Comment by octavn** [comment]
With the [Pipe](https://addpipe.com) video recording client we've resorted to showing the camera stream picture in picture during playback (after a recording) to:

- avoid requesting camera & microphone access multiple times on Firefox.
- avoid the insecurity & confusion of having your camera light on but not seeing your steram on screen

**Comment by heeringa0** [comment]
I looked at:
https://higuma.github.io/wav-audio-encoder-js/

When checking Microphone permission is asked only once. Only when the site is refreshed (with F5) permission is asked again.

**Comment by octavn** [comment]
The web app @ the link you've posted does not work for me on the latest versions of Chrome and Firefox. **It does not ask for camera/microphone permissions.** Recording _starts_ but the resulting recording is empty.
