### ISSUE TITLE
Silent recording on Working on Safari on Mac

### ISSUE THREAD

**Issue by ManicMapple** [addpipe/simple-web-audio-recorder-demo#5]
Safari 12.1.2 
Mac OsX 10.14.6

Steps to reproduce:

1.  Goto https://addpipe.com/simple-web-audio-recorder-demo/
2. Record sound in wav or mp3
3. Play sound in Browser
4. Download and play in mac os
5. Yes, speakers are on!

Efffects
* All recordings are silent
* Chrome on mac works
* iphone (all version I have tested) work

**Comment by TPETb** [comment]
In case someone reads it, this issue doesn't reproduce in Safari Version 13.0.3 (15608.3.10.1.4)

**Comment by ManicMapple** [comment]
I found out that I did not check for webkit-audiocontext avaiablility... my fault
